# Generated by Django 5.2.9 on 2025-12-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spendly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
